name = "PhyloDiamond"
uuid = "5fd89c64-9bfa-4c3b-9406-7e573fc4f4af"
authors = ["zwu363 <79068497+zwu363@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
PhyloPlots = "c0d5b6db-e3fc-52bc-a87d-1d050989ed3b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"
CSV = "0.10.9"
Combinatorics = "1.0.2"
DataFrames = "1.4.4"
Distributions = "0.25.80"
Documenter = "0.27.24"
Example = "0.5.3"
PhyloNetworks = "0.15.3"
PhyloPlots = "1.0.0"
StatsBase = "0.33.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
